config/routes.rb
Rails.application.routes.draw do
  get 'abouts/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'posts#index'

  resources :posts do
    resources :comments
  end

  get 'posts/year/:year', to: 'posts#date', as: 'year'

  get 'posts/category/:cid', to: 'posts#category', as: 'category'

  get 'about', to: 'abouts#index', as: 'about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  #与博客的关系
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  #验证
  validates :body, presence: true

  belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
  before_save :getdescription, on: :create

  #验证
  validates :title, presence: true
  validates :body, presence: true
  #一个博客一个分类
  belongs_to :category
  #一个博客有多个评论
  has_many :comments

  #设置分页数据
  paginates_per 4

  #如果摘要为空则自动生成
  def getdescription
    if self.description.nil?
      self.description = self.body[0..100]
    end
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(post_params)
    redirect_to post_path(@post)
  end

  private

  #健壮参数
  def post_params
    params.require(:comment).permit(:name, :email, :url, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    #按创建时间倒叙排列
    @posts = Post.all.order(created_at: :desc).page params[:page]
    #@posts = Post.paginate(page: params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    #阅读计数
    @post = Post.find(params[:id])
    @post.increment!(:readcount)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #根据时间查询(年归档)
  def date
    @posts = Post.where('extract(year from created_at) = ?', params[:year]).order(created_at: :desc).page params[:page]
  end

  #根据分类查询
  def category
    @posts = Post.where('category_id = ?', params[:cid]).order(created_at: :desc).page params[:page]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by_created_at(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  #markdown 解析
  def  markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                    no_intra_emphasis: true,
                                    fenced_code_blocks: true,
                                    disable_indented_code_blocks: true,
                                    autolink: true,
                                    tables: true,
                                    underline: true,
                                    highlight: true
                                   )
   return markdown.render(text).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  #归档
  def archives
    @postlist = Post.group_by_year(:created_at, series: false, format: "%Y").count
  end

  #分类归档
  def getcategory
    @postlist = Post.group(:category).count
  end
end

app/views/abouts/index.html.erb
<div class="content-body">
  <div class="container">
    <div class="row">
      <main class="col-md-12">
        <h1 class="page-title">关于我</h1>
        <article class="post">
          <div class="entry-content clearfix">
            <figure class="img-responsive-center">

            </figure>
           <p>

           </p>
            <div class="height-40px"></div>
            <h2 class="title text-center">Social</h2>

          </div>
        </article>
      </main>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>践者无敌</title>
    <%= csrf_meta_tags %>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
    <%= render "shared/head" %>
    <%= yield %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/category.html.erb
<p id="notice"><%= notice %></p>
<div class="content-body">
  <div class="container">
    <div class="row">
      <!--博客列表-->
      <main class="col-md-8">
        <% @posts.each do |post| %>
          <article class="post post-1">
            <header class="entry-header">
              <h1 class="entry-title">
                <a href="<%= post_path(post) %>" class="face"><%= post.title %></a>
              </h1>
              <div class="entry-meta ">
                <span class="post-category"><%= post.category.name %></span>
                <span class="post-date"><time class="entry-date"
                ><%= post.created_at.strftime("%F %T") %></time></span>
                <span class="comments-link"><%= post.readcount %> 阅读</span>
                <span class="views-count"><%= post.comments.count %> 评论</span>
              </div>
            </header>
            <div class="entry-content clearfix">
              <p><%= post.description %></p>
            </div>
          </article>
        <% end %>
        <div class="facepagination" >
          <%= paginate @posts, window: 2 %>
        </div>
      </main>
      <%= render "shared/targ" %>
    </div>
  </div>
</div>

app/views/posts/date.html.erb
<p id="notice"><%= notice %></p>
<div class="content-body">
  <div class="container">
    <div class="row">
      <!--博客列表-->
      <main class="col-md-8">
        <% @posts.each do |post| %>
          <article class="post post-1">
            <header class="entry-header">
              <h1 class="entry-title">
                <a href="<%= post_path(post) %>" class="face"><%= post.title %></a>
              </h1>
              <div class="entry-meta ">
                <span class="post-category"><%= post.category.name %></span>
                <span class="post-date"><time class="entry-date"
                ><%= post.created_at.strftime("%F %T") %></time></span>
                <span class="comments-link"><%= post.readcount %> 阅读</span>
                <span class="views-count"><%= post.comments.count %> 评论</span>
              </div>
            </header>
            <div class="entry-content clearfix">
              <p><%= post.description %></p>
            </div>
          </article>
        <% end %>
        <div class="facepagination" >
          <%= paginate @posts, window: 2 %>
        </div>
      </main>
      <%= render "shared/targ" %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="content-body">
    <div class="container">
        <div class="row">
          <!--博客列表-->
            <main class="col-md-8">
                <% @posts.each do |post| %>
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="<%= post_path(post) %>" class="face"><%= post.title %></a>
                        </h1>
                        <div class="entry-meta ">
                            <span class="post-category"><%= post.category.name %></span>
                            <span class="post-date"><time class="entry-date"
                                                                      ><%= post.created_at.strftime("%F %T") %></time></span>
                            <span class="comments-link"><%= post.readcount %> 阅读</span>
                            <span class="views-count"><%= post.comments.count %> 评论</span>
                        </div>
                    </header>
                  <div class="entry-content clearfix">
                    <p><%= post.description %></p>
                  </div>
                </article>
                <% end %>
              <div class="facepagination" >
                <%= paginate @posts, outer_window: 3%>
              </div>
            </main>
            <%= render "shared/targ" %>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="content-body">
  <div class="container">
    <div class="row">
      <main class="col-md-8">
        <article class="post post-1">
          <header class="entry-header">
            <h1 class="entry-title"><%= @post.title %></h1>
            <div class="entry-meta">
              <span class="post-category"><%= @post.category.name %></span>
              <span class="post-date"><time class="entry-date"
                                                        ><%= @post.created_at.strftime("%F %T") %></time></span>
              <span class="views-count"><%= @post.readcount %> 阅读</span>
              <span class="comments-link"><%= @post.comments.count %> 评论</span>
            </div>
          </header>
          <div class="entry-content clearfix">
            <%= markdown(@post.body) %>
          </div>
        </article>
        <section class="comment-area" id="comment-area">
          <hr>
          <div class="comment-list-panel">
            <h3>评论列表，共 <span><%= @post.comments.count %></span> 条评论</h3>
            <ul class="comment-list list-unstyled">
              <% @post.comments.each do |comm| %>
                <li class="comment-item">
                  <span class="nickname"><%= comm.name %></span>
                  <time class="submit-date" datetime="2012-11-09T23:15:57+00:00"><%= comm.created_at %></time>
                  <div class="text">
                    <%= comm.body %>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
          <hr>
          <h3>发表评论</h3>
          <%= simple_form_for ([@post, @post.comments.build]) do |f| %>

            <div class="row">
              <div class="col-md-4">
                <%= f.input :name, label: '姓名', input_html: {class: "form-control"}  %>
              </div>
              <div class="col-md-4">
                <%= f.input :email, label: '邮件', input_html: {class: "form-control"} %>
              </div>
              <div class="col-md-4">
                <%= f.input :url, label: '网址', input_html: {class: "form-control"} %>
              </div>
              <div class="col-md-12">
                <%= f.input :body, label:false, placeholder: '请输入留言', input_html: {class: "form-control", rows: 10, cols: 8}%>
                <%= f.button :submit, "回复", class: "btn btn-primary", data: {disable_with: "回复中..."} %>
              </div>
            </div>    <!-- row -->
          <% end %>

        </section>
      </main>
      <%= render "shared/targ" %>
    </div>
  </div>
</div>

app/views/shared/_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2018 -
                    <a href="http://luoke.one/" title="践者无敌" target="_blank">践者无敌</a>
                </p>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_head.html.erb
<div class="container">
    <header id="site-header">
                <nav class="navbar navbar-inverse navbar-fixed-top" >
                  <div class="container">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle" data-toggle="collapse"
                                data-target="#bs-example-navbar-collapse-1">
                          <span class="sr-only">切换导航</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </button>
                      <a class="navbar-brand" href="<%= root_url %>">践者无敌</a>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a href="<%= root_url %>" data-hover="首页" >博客</a></li>
                          <!--
                            <li class=""><a href="<%= about_url %>" data-hover="关于" >关于</a></li>
                            -->
                        </ul>
                    </div>
                  </div>
                </nav>
    </header>
</div>

app/views/shared/_targ.html.erb
<!--右边-->
<aside class="col-md-4">
<!--  <div class="widget widget-recent-posts">-->
<!--    <h3 class="widget-title">最新文章</h3>-->
<!--    <ul>-->
<!--      <li>-->
<!--        <a href="#">Django 博客开发入门教程：前言</a>-->
<!--      </li>-->
<!--      <li>-->
<!--        <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>-->
<!--      </li>-->
<!--      <li>-->
<!--        <a href="#">部署 Django 博客</a>-->
<!--      </li>-->
<!--    </ul>-->
<!--  </div>-->
  <div class="widget widget-archives">
    <h3 class="widget-title">归档</h3>
    <ul>
      <% archives.each do |pl| %>
        <li>
          <a href="<%= year_path(pl[0]) %>">
          <%= pl[0] %> ( <%= pl[1] %> )
          </a>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="widget widget-category">
    <h3 class="widget-title">分类</h3>
    <ul>
      <% getcategory.each do |ca| %>
        <li>
          <a href="<%= category_path(ca[0]) %>">
            <%= ca[0].name %> ( <%= ca[1] %> )
          </a>
        </li>
      <% end %>
    </ul>
  </div>

<!--  <div class="widget widget-tag-cloud">-->
<!--    <h3 class="widget-title">标签云</h3>-->
<!--    <ul>-->
<!--      <li>-->
<!--        <a href="#">Django</a>-->
<!--      </li>-->
<!--      <li>-->
<!--        <a href="#">Python</a>-->
<!--      </li>-->
<!--      <li>-->
<!--        <a href="#">Java</a>-->
<!--      </li>-->
<!--      <li>-->
<!--        <a href="#">笔记</a>-->
<!--      </li>-->
<!--      <li>-->
<!--        <a href="#">文档</a>-->
<!--      </li>-->
<!--      <li>-->
<!--        <a href="#">AngularJS</a>-->
<!--      </li>-->
<!--      <li>-->
<!--        <a href="#">CSS</a>-->
<!--      </li>-->
<!--      <li>-->
<!--        <a href="#">JavaScript</a>-->
<!--      </li>-->
<!--      <li>-->
<!--        <a href="#">Snippet</a>-->
<!--      </li>-->
<!--      <li>-->
<!--        <a href="#">jQuery</a>-->
<!--      </li>-->
<!--    </ul>-->
<!--  </div>-->
<!--  <div class="rss">-->
<!--    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>-->
<!--  </div>-->
</aside>